# Authors: Fredrik Mørstad & Fredrik Fasteraune

version: "3.5"
services:
  demo:
    container_name: assignment-1
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    volumes:
      - ../:/src
